-- Modifications To user_type
INSERT INTO user_type (type) VALUES ('USER'), ('ADMIN'), ('PRODUCER'), ('PRODUCER_VIP');
-- Poner el usuario que va a conectarse a la base de datos
--REVOKE INSERT, UPDATE, DELETE ON user_type FROM 'username'@'hostname';

-- Modifications state_request
INSERT INTO state_request (state) VALUES ('PENDING'), ('ACCEPTED'), ('DECLINED');
--REVOKE INSERT, UPDATE, DELETE ON state_request FROM 'username'@'hostname';

INSERT INTO user (total_authorization, user_type_id, email, lastname, name, address, password) VALUES (true, 2, 'admin@gmail.com', 'Admin', 'Admin', 'Direccion', 'admin');
INSERT INTO plantation (area, harvest_type, irrigation_type, production_type, details) VALUES ('100 sqm', 'organic', 'drip', 'type1', 'semillas de tomate para cultivo en verano'), ('200 sqm', 'organic', 'drip', 'type2', 'semillas de zanahoria para cultivo en primavera'), ('150 sqm', 'organic', 'drip', 'type3', 'semillas de lechuga para plantacion en otonio'), ('300 sqm', 'conventional', 'sprinkler', 'type1', 'semillas de maiz para cosecha en verano'), ('250 sqm', 'conventional', 'sprinkler', 'type2', 'semillas de pepino para plantacion en primavera'), ('120 sqm', 'conventional', 'sprinkler', 'type3', 'semillas de calabaza para cultivo en verano'), ('220 sqm', 'hydroponic', 'drip', 'type1', 'semillas de papa para plantacion en otonio'), ('180 sqm', 'hydroponic', 'drip', 'type2', 'semillas de fresa para cosecha en primavera'), ('270 sqm', 'hydroponic', 'sprinkler', 'type1', 'semillas de sandia para cultivo en verano'), ('190 sqm', 'hydroponic', 'sprinkler', 'type2', 'semillas de rabano para plantacion en otonio');

--INSERT INTO plantation (plant_type, seasson, water_amount, details) VALUES  ('tomate', 'verano', 1500, 'semillas de tomate para cultivo en verano'), ('zanahoria', 'primavera', 1200, 'semillas de zanahoria para cultivo en primavera'), ('lechuga', 'otonio', 1000, 'semillas de lechuga para plantacion en otonio'), ('maiz', 'verano', 1800, 'semillas de maiz para cosecha en verano'), ('pepino', 'primavera', 1400, 'semillas de pepino para plantacion en primavera'), ('calabaza', 'verano', 1600, 'semillas de calabaza para cultivo en verano'), ('papa', 'otonio', 1300, 'semillas de papa para plantacion en otonio'), ('fresa', 'primavera', 1100, 'semillas de fresa para cosecha en primavera'), ('sandia', 'verano', 1700, 'semillas de sandia para cultivo en verano'), ('rabano', 'otonio', 1250, 'semillas de rabano para plantacion en otonio');
INSERT INTO image (id, url) VALUES ('publications/oaduochtlivtwaob7ouj', 'https://res.cloudinary.com/dvckhdihm/image/upload/v1711212052/publications/oaduochtlivtwaob7ouj.png'), ('publications/khmjecxfpw1c2lh2byk0', 'https://res.cloudinary.com/dvckhdihm/image/upload/v1711212773/publications/khmjecxfpw1c2lh2byk0.png'), ('publications/ehcjqq4jkcy2aomkyxo3', 'https://res.cloudinary.com/dvckhdihm/image/upload/v1711212837/publications/ehcjqq4jkcy2aomkyxo3.png'), ('publications/ezf6x1rhblki1p3l3kzi', 'https://res.cloudinary.com/dvckhdihm/image/upload/v1711212872/publications/ezf6x1rhblki1p3l3kzi.png'), ('publications/y4in5jrlfi14eag2vnwl', 'https://res.cloudinary.com/dvckhdihm/image/upload/v1711212905/publications/y4in5jrlfi14eag2vnwl.png'), ('publications/uui7ncpdsa4ba5zhkq9p', 'https://res.cloudinary.com/dvckhdihm/image/upload/v1711212926/publications/uui7ncpdsa4ba5zhkq9p.png');
INSERT INTO publication (title, plantation_id, author_id, publication_date, visibility, main_image_id, score, authorization_status_id) VALUES ('Cultivo de tomates', 1, 1, '2024-03-23 10:00:00', true, 'publications/oaduochtlivtwaob7ouj', 1, 2), ('Cultivo de zanahorias', 2, 1, '2024-03-23 11:00:00', true, 'publications/khmjecxfpw1c2lh2byk0', 2, 1), ('Plantacion de lechugas', 3, 1, '2024-03-23 12:00:00', true, 'publications/ehcjqq4jkcy2aomkyxo3', 3, 1), ('Cosecha de maiz', 4, 1, '2024-03-23 13:00:00', true, 'publications/ezf6x1rhblki1p3l3kzi', 4, 2), ('Plantacion de pepinos', 5, 1, '2024-03-23 14:00:00', true, 'publications/y4in5jrlfi14eag2vnwl', 5,2), ('Cultivo de calabazas', 6, 1, '2024-03-23 15:00:00', true, 'publications/uui7ncpdsa4ba5zhkq9p', 6, 2);
